import "../styles/globals.css";
import "bootstrap/dist/css/bootstrap.css";

import { Web3Provider } from "@ethersproject/providers";
import { Web3ReactProvider } from "@web3-react/core";
import TopNav from "../components/Navbar/TopNav";
import { AuthContextProvider } from "../context/AuthContext";
import { useRouter } from "next/router";
import { SellRegisterContextProvider } from "../context/SellRegistrationContext";
import Head from "next/head";
import { SSRProvider } from "react-bootstrap";
import { createContext, useContext } from "react";

const getLibrary = async (provider) => {
  return new Web3Provider(provider);
};


function MyApp({ Component, pageProps }) {
  const router = useRouter();

  return (
    <>
      <Head>
        <title>Nft Housing</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        {/* <script
          src="https://code.jquery.com/jquery-3.6.0.min.js"
          integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
          crossorigin="anonymous"
        ></script> */}
        {/* <script
          src="https://html2canvas.hertzen.com/dist/html2canvas.js"
          type="text/javascript"
        ></script> */}
      </Head>

      <SSRProvider>
          <Web3ReactProvider getLibrary={getLibrary}>
            <AuthContextProvider>
              <SellRegisterContextProvider>
                <TopNav />
                <Component {...pageProps} />
              </SellRegisterContextProvider>
            </AuthContextProvider>
          </Web3ReactProvider>
      </SSRProvider>

    </>
  );
}


export default MyApp;