import Head from 'next/head'
import Image from 'next/image'
import { SectionFour } from '../components/Home/SectionFour'
import { SectionOne } from '../components/Home/SectionOne'
import { SectionThree } from '../components/Home/SectionThree'
import { SectionTwo } from '../components/Home/SectionTwo'
import styles from '../styles/Home.module.css'

export default function Home() {
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Nft Housing</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <SectionOne />
        <div style={{height: '100px'}}></div>
        <SectionTwo />
        <div style={{height: '100px'}}></div>
        <SectionThree />
        {/* <div style={{height: '100px'}}></div> */}
        <SectionFour />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
